### ISSUE TITLE
Manifest Merger failed

### ISSUE THREAD

**Issue by joehbenti** [brookmg/Soccer-Ethiopia-API#12]
## I get this error when i try include your API

error is shown on this line in my dependencies list
 implementation 'com.android.support:appcompat-v7:28.0.0'

ACTUAL ERROR

ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:20:5-84:19 to override.

**Comment by brookmg** [comment]
Which version are you using? V0.4.1 or V0.4.0

**Comment by joehbenti** [comment]
V0.4.1

**Comment by brookmg** [comment]
The problem seems to be caused because of androidx. AndroidX is the new artifact for support libraries. You should consider migrating your project. How to migrate: https://developer.android.com/jetpack/androidx/migrate ... or try out the previous version v0.4.0

**Comment by joehbenti** [comment]
The older version works. Thank you

**Comment by brookmg** [comment]
No prob. But to keep up with latest releases check out androidx 👍
