### ISSUE TITLE
centralize .gitignore

### ISSUE THREAD

**Issue by mikiTesf** [brookmg/Soccer-Ethiopia-API#8]
Why do you need separate .gitignore files in every directory? You only need 1 in the root directory.

**Comment by brookmg** [comment]
/app is a sample android application that implements the api ... and /soccerethiopiaapi is the module where the api is located ... i believe it's better to give them there own ignore config to minimize confusion

**Comment by brookmg** [comment]
But now that i think of it, it's pointless... so pull request the changes that you think should be made 🤓
